config/routes.rb
Todos::Application.routes.draw do

  match '/auth/:provider/callback', to: "sessions#new" 
  match '/auth/failure', to:  'sessions#failure'
  resources :reset_passwords

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get "welcome/index"
    get  "logout"   => "sessions#destroy", :as => "logout"
    get  "login"    => "sessions#new",     :as => "login"
    post "login"    => "sessions#create",  :as => "login"
    get  "signup"   => "users#new",        :as => "signup"
    get  "profile"  => "users#show",       :as => "profile"
    
    
    resources :sessions
    resources :users 
    resources :tasks


    root :to => 'welcome#index'
  end
  
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| 
    !req.path.starts_with? "/#{I18n.default_locale}/" and !req.path.starts_with? "/auth/"
  }
  match '', to: redirect("/#{I18n.default_locale}")
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  active     :boolean          default(TRUE), not null
#  created_at :datetime         not null
#  deleted_at :datetime
#  id         :integer          not null, primary key
#  status     :string(10)       not null
#  title      :string(100)      not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#

#Globalize::ActiveRecord::Translation.class_eval do
#  attr_accessible :locale
#end

class Task < ActiveRecord::Base

 
  COMPLETED = 'completed'
  PENDING   = 'pending'

  attr_accessible :title


  validates :title, :presence => true
  before_create :set_default_status

  def update_status(new_status)
    return false  unless [COMPLETED, PENDING].include?(new_status)
    self.status = new_status
    self.save!
  end
  
  def pending?
    status == PENDING
  end
  
  def completed?
    status == COMPLETED
  end

  private 
  def set_default_status
    self.status = PENDING unless status
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  helper_method :cache_key

#caches_action :index, :layout => false, :cache_path => proc{|x| tasks_url(I18n.locale, session[:user_id]) }

  # GET /tasks
  # GET /tasks.json
  def index
    all_tasks
    @task            = Task.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = tasks.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    all_tasks
    @task = tasks.find(params[:id])
    status = params[:status]
    if ['pending','completed'].include?(status)  
      @task.update_status(status)
      expire_task_cache
      redirect_to tasks_url, notice: 'Task was successfully updated.' and return
    end
    render 'index' and return
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        expire_task_cache
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        all_tasks
        format.html { render action: "index" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        expire_task_cache
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        tasks
        format.html { render action: "index" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    expire_task_cache
    @task = tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  
  private
  def tasks
    @current_user.tasks
  end
  
  def all_tasks
    @pending_tasks   = tasks.pending
    @completed_tasks = tasks.completed
  end
  
  def expire_task_cache
    expire_fragment(cache_key)
    #expire_action tasks_url(I18n.locale, session[:user_id]) 
  end
  
  def cache_key
    "#{current_user.id}_#{I18n.locale}_tasks"
  end
  

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class='form-container'>
  <%= form_for(@task) do |f| -%>
    <table cellpadding='0' cellspacing='0' border='0'>
      <tr>
        <td colspan='3' class="title"><%= ['edit','update'].include?(params[:action]) ? 'Edit Task' : t('.add_new_task_title') %></td>
      </tr>  
      <tr>
        <td valign='top'><%= f.text_field :title %></td>
        <td><%= f.submit (['edit','update'].include?(params[:action]) ? 'Update' : t('.add_button')), {:class => 'button'} -%></td>
        <td><%= f.submit t('.cancel_button'), {:class => 'button cancel-btn'} -%></td>
      </tr>  
    </table>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= render 'shared/alert' %>

<% cache(cache_key) do %>
  <%= render 'form', :add_new_task_title => t('.add_new_task_title')  %> 
  <table width='90%' cellspacing='0' cellpadding='5'>
    <tr>
      <td valign='top' width='50%' id="pending_tasks_list">
      
        <h2><%= t ".pending_title" %> </h2>
        <table width='95%' cellspacing='2' cellpadding='4' class="listings" id="pending_tasks_table">
          <% @pending_tasks.each do |task| %>
            <tr class="<%= cycle('even', 'odd') %>">
              <td width='80%'><%= task.title %></td>
              <td><%= link_to image_tag("icon-completed.png", {:title => 'Mark as completed', 
                                                               :name => "mark_as_completed"}), 
                              edit_task_path(task, :status => 'completed') %>
              </td>
              <td><%= link_to image_tag("icon_edit_small.png", {:title => 'Edit', :name => 'Edit'}),
                               edit_task_path(task) %>
               </td>
              <td><%= link_to image_tag("delete.png", {:title => 'Delete'}), 
                              task, confirm: 'Are you sure?', method: :delete %>
              </td>
            </tr>
          <% end %>
        </table>
        
      </td>

      <td width='50%' valign='top' id="completed_tasks_list">
      
        <h2><%= t ".completed_title" %></h2>
        <table width='95%' cellspacing='2' cellpadding='4' class="listings" id="completed_tasks_table">
          <% @completed_tasks.each do |task| %>
            <tr class="<%= cycle('even', 'odd') %>">
              <td width='80%'><%= task.title %></td>
              <td><%= link_to image_tag("icon-pending.png", {:title => 'Mark as pending'}),
                              edit_task_path(task, :status => 'pending') %>
            </td>
          </tr>
        <% end %>
        </table>
        
      </td>
    </tr>
  </table>

<% end %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Active:</b>
  <%= @task.active %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @task.deleted_at %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>