config/routes.rb
Todos::Application.routes.draw do

  match '/auth/:provider/callback', to: "sessions#new" 
  match '/auth/failure', to:  'sessions#failure'
  resources :reset_passwords

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get "welcome/index"
    get  "logout"   => "sessions#destroy", :as => "logout"
    get  "login"    => "sessions#new",     :as => "login"
    post "login"    => "sessions#create",  :as => "login"
    get  "signup"   => "users#new",        :as => "signup"
    get  "profile"  => "users#show",       :as => "profile"
    
    
    resources :sessions
    resources :users 
    resources :tasks


    root :to => 'welcome#index'
  end
  
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| 
    !req.path.starts_with? "/#{I18n.default_locale}/" and !req.path.starts_with? "/auth/"
  }
  match '', to: redirect("/#{I18n.default_locale}")
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController

  skip_before_filter :authenticate_user!
  
  def new
  end
  
  def create
    unless params[:email].present?
      flash.now.alert = 'Enter your email id to continue..'
      render 'new' and return
    end
    user = User.find_by_email(params[:email])
    user.send_new_password if user
    redirect_to new_reset_password_url, :notice => "You will receive an email with password 
                                                    reset instruction if your email exist 
                                                    in our database"
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_expired?
      redirect_to new_reset_password_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end

end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/views/reset_passwords/edit.html.erb
<h1 class='form-title'> Reset my password </h1>

 <%= simple_form_for @user,  :url => reset_password_path(params[:id]) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :password, :input_html => {:autocomplete => "off"} %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,'Change Password', {:class => 'register-btn'} %>
  </div>
<% end %>

app/views/reset_passwords/new.html.erb
<h1 class='form-title'> Reset my password </h1>
 <div class='simple_form signin-form'>
 <%= render 'shared/alert' %>
  <div style='float:left'>
    <%= form_tag reset_passwords_path do  %>
      <div class="form-container">
        <div><label>Your Email</label></div>
        <div>
          <%= text_field_tag 'email', params[:email], {:autocomplete => "off"} %>
        </div>
        <div class='form-actions'>  
          <%= button_tag 'Reset', {:type=>'submit', :class => 'btn signin-btn'} %>
        </div>   
      </div>
    <% end %>
    
  </div>
 </div>  